config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  resources :homepage, only: [:index, :new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
	include ActiveModel::Model
  attr_accessor :name, :email, :phone_number, :body
  validates :name, :email, :body, presence: true

  def headers
    {
      subject: 'My Contact Form',
      to: 'lazo_christian@yahoo.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

class HomepageController < ApplicationController
  def index
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to root_path
      flash[:notice] = "Thank you for your message. I'll get back to you soon!"
    else
      flash[:notice] = "Message did not send."
      render root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(
      :name,
      :email,
      :body
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/homepage/_contact_form.html.haml
.container
  .form
    .contact-title#contact-form
      %h2.contact-title.text-center Get in Touch
    .contact-form
      = form_for @message, url: homepage_index_path, remote: true do |f|
        = f.text_field  :name, required: true,
          class: "mb-4", placeholder: 'Name', type: 'text', id: 'custom-form'
        = f.text_field :email, required: true,
          class: "mb-4", placeholder: 'E-mail', type: 'email', id:'custom-form'
        = f.text_area :body, rows: 3, cols: 40, required: true,
          class: "mb-4", placeholder: "Send a message", id: 'custom-form'

        .col-sm
          = f.submit 'Send Message', class: 'btn btn-dark'
  .col-md-6#flash-message
    = render partial: 'flash'

app/views/homepage/_flash.html.haml
- flash.each do |message_type, message|
  = content_tag(:div, message, class: "alert alert-#{message_type}")

app/views/homepage/_footer.html.haml
%footer
  .row.justify-content-center
    .footer-nav
      %ul
        %li
          = link_to('Home', root_path)
        %li
          = link_to('Contact Me', root_path)
  .row.justify-content-center
    .copyright-line
      %p &copy 2019 Christian Lazo. All rights reserved. Software Developer
  .row.justify-content-center
    .social-media
      %a{:href => 'https://github.com/chrislazo22'}
        %i.fa.fa-github{"aria-hidden" => "true"}
      %a{:href => 'https://www.linkedin.com/in/christian-lazo/'}
        %i.fa.fa-linkedin{"aria-hidden" => "true"}
      %a{:href => 'https://twitter.com/crunchy1chris'}
        %i.fa.fa-twitter{"aria-hidden" => "true"}

app/views/homepage/index.html.haml
.wrapper
  = render partial: 'layouts/navbar'
  %header
    .flex-wrapper
      .inner
        .content
          .row
            .col-sm
              %h1.first-name Chris
            .col-sm
              %h1.last-name Lazo
          .row.ml-auto.header
            .col-sm
              %h2.heading Software Developer

%section.contact-me.mb-4
  = render partial: 'contact_form'

= render partial: 'footer'

app/views/layouts/_navbar.html.haml
%nav.navbar.my-nav.navbar-expand-lg.navbar-light
  %a.navbar-brand{:href => "#"}
    = image_tag('https://s3-us-west-1.amazonaws.com/chrislazo-assets/logo2.png', size: '55')

  %button.navbar-toggler{"aria-controls" => "navbarNav",
    "aria-expanded" => "false",
    "aria-label" => "Toggle navigation",
    "data-target" => "#navbarNav",
    "data-toggle" => "collapse",
    type: "button"}
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#navbarNav
    %ul.nav.navbar-nav.ml-auto
      %li.nav-item{class: "#{'active' if params[:action] == 'index'}"}
        = link_to('Home', root_path, {class: 'nav-link'})
      %li.nav-item
        %a.nav-link{href: "#contact-form"} Contact Me

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/


    %title ChrisLazo

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body{class: "#{controller.controller_name}",
        id: "#{controller.action_name}"}
    = yield